export const theme = {
  colors: {
    primary: '#10B981',
    primaryDark: '#059669',
    primaryLight: '#34D399',
    secondary: '#FBBF24',
    secondaryDark: '#F59E0B',
    secondaryLight: '#FCD34D',
    accent: '#84CC16',
    background: '#F9FAFB',
    surface: '#FFFFFF',
    text: {
      primary: '#111827',
      secondary: '#6B7280',
      light: '#9CA3AF',
      inverse: '#FFFFFF',
    },
    success: '#10B981',
    warning: '#FBBF24',
    error: '#EF4444',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontFamily: 'Inter-Bold',
      lineHeight: 38,
    },
    h2: {
      fontSize: 24,
      fontFamily: 'Inter-Bold',
      lineHeight: 32,
    },
    h3: {
      fontSize: 20,
      fontFamily: 'Inter-SemiBold',
      lineHeight: 28,
    },
    body: {
      fontSize: 16,
      fontFamily: 'Inter-Regular',
      lineHeight: 24,
    },
    bodySmall: {
      fontSize: 14,
      fontFamily: 'Inter-Regular',
      lineHeight: 20,
    },
    caption: {
      fontSize: 12,
      fontFamily: 'Inter-Regular',
      lineHeight: 16,
    },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
  },
};
