import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = '@app_language';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage && ['en', 'si', 'ta'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
      if (value === undefined) {
        return key;
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

const translations: Record<Language, any> = {
  en: {
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      submit: 'Submit',
      delete: 'Delete',
      edit: 'Edit',
      back: 'Back',
      logout: 'Logout',
      success: 'Success',
      error: 'Error',
      refresh: 'Refresh',
    },
    admin: {
      dashboard: 'Admin Dashboard',
      systemManagement: 'SYSTEM MANAGEMENT',
      todayMeals: "Today's Meals",
      totalMealsServed: 'Total Meals Served',
      totalDonations: 'Total Donations',
      pendingRequests: 'Pending Requests',
      systemStatistics: 'System Statistics',
      totalUsers: 'Total Users',
      totalSchools: 'Total Schools',
      pendingSchoolApprovals: 'Pending School Approvals',
      usersByRole: 'Users by Role',
      admins: 'Admins',
      principals: 'Principals',
      teachers: 'Teachers',
      donors: 'Donors',
      parents: 'Parents',
      quickActions: 'Quick Actions',
      userManagement: 'User Management',
      userManagementDesc: 'Add, edit, and manage users',
      schoolManagement: 'School Management',
      schoolManagementDesc: 'Approve schools',
      donationManagement: 'Donation Management',
      donationManagementDesc: 'Track and manage donations',
      reportsAnalytics: 'Reports & Analytics',
      reportsAnalyticsDesc: 'Generate comprehensive reports',
      accessDenied: 'Access Denied: Admin Only',
      totalRaised: 'Total Raised',
      mealsFunded: 'Meals Funded',
      activeRequests: 'Active Requests',
      donations: 'Donations',
      requests: 'Requests',
      noDonations: 'No donations yet',
      noDonationRequests: 'No donation requests',
      donor: 'Donor',
      email: 'Email',
      school: 'School',
      message: 'Message',
      principal: 'Principal',
      purpose: 'Purpose',
      targetDate: 'Target Date',
      description: 'Description',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      total: 'Total',
      noSchools: 'No schools found',
      confirmApproval: 'Confirm Approval',
      approveSchool: 'Approve',
      confirmRejection: 'Confirm Rejection',
      rejectSchool: 'Reject',
      schoolApproved: 'School approved successfully',
      schoolRejected: 'School rejected',
      failedToApprove: 'Failed to approve school',
      failedToReject: 'Failed to reject school',
      submitted: 'Submitted',
      addNewUser: 'Add New User',
      editUser: 'Edit User',
      name: 'Name',
      password: 'Password',
      role: 'Role',
      schoolOptional: 'School (Optional)',
      none: 'None',
      create: 'Create',
      update: 'Update',
      confirmDelete: 'Confirm Delete',
      deleteMessage: 'Are you sure you want to delete',
      userCreated: 'User created successfully',
      userUpdated: 'User updated successfully',
      userDeleted: 'User deleted successfully',
      fillRequired: 'Please fill all required fields',
      passwordRequired: 'Password is required for new users',
      users: 'users',
      schools: 'schools',
    },
    reports: {
      generatedReports: 'Generated Reports',
      generateWithAI: 'Generate with AI',
      report: 'Report',
      aiGenerated: 'AI Generated',
      mealsServed: 'Meals Served',
      shortages: 'Shortages',
      feedbackSummary: 'Feedback Summary',
      downloadPDF: 'Download PDF',
      share: 'Share',
      noReports: 'No reports generated yet',
      useAIPrompt: 'Use AI to generate your first report',
      generateAIReport: 'Generate AI Report',
      reportPeriod: 'Report Period (Days)',
      dataAnalyzed: 'Data from the last',
      daysAnalyzed: 'days will be analyzed',
      generateReport: 'Generate Report',
      reportGenerated: 'Report Generated!',
      reportSuccess: 'Your AI-powered report has been successfully generated. Choose an option below to share or save it.',
      shareReport: 'Share Report',
      printSavePDF: 'Print/Save as PDF',
      shareViaPDF: 'Share PDF via apps',
      savePDF: 'Save & Share PDF',
      close: 'Close',
      accessDeniedReports: 'Access Denied',
      noPermission: "You don't have permission to view this page.",
      failedGenerate: 'Failed to generate report. Please try again.',
      failedShare: 'Failed to share report. Please try again.',
      failedDownload: 'Failed to download report. Please try again.',
    },
    feedback: {
      schoolFeedback: 'School Feedback',
      allFeedback: 'All Feedback',
      pending: 'Pending',
      reviewed: 'Reviewed',
      noFeedback: 'No feedback yet',
      school: 'School',
      submittedBy: 'Submitted By',
      status: 'Status',
      markReviewed: 'Mark as Reviewed',
      feedbackMarked: 'Feedback marked as reviewed',
      failedMark: 'Failed to mark feedback',
    },
    donations: {
      donations: 'Donations',
      claimDonation: 'Claim Donation',
      noDonations: 'No donations available',
      donatedBy: 'Donated By',
      amount: 'Amount',
      forStudents: 'For Students',
      claimSuccess: 'Donation claimed successfully!',
      failedClaim: 'Failed to claim donation',
    },
    parent: {
      hello: 'Hello',
      mealInfo: "'s Meal Info",
      yourAccessCode: 'Your Access Code',
      grade: 'Grade',
      age: 'Age',
      todayMeal: "Today's Meal",
      amount: 'Amount',
      for: 'For',
      students: 'Students',
      donatedBy: 'Donated By',
      ratings: 'ratings',
      howWasMeal: 'How was the meal?',
      tapStars: 'Tap the stars to rate',
      poor: 'Poor',
      fair: 'Fair',
      good: 'Good',
      veryGood: 'Very Good',
      excellent: 'Excellent',
      addComment: 'Add your comment (optional)',
      submitRating: 'Submit Rating',
      noMealToday: 'No Meal Today',
      noMealScheduled: 'There is no meal scheduled for today',
      mealStatus: 'Meal Status',
      mealServed: '✓ Meal Served',
      notServedYet: '⏳ Not Served Yet',
      at: 'at',
      teacherNote: "Teacher's Note:",
      upcomingMeals: 'Upcoming Meals',
      by: 'by',
      itemsPlanned: 'item(s) planned',
      allergyInfo: 'Allergy Info',
      allergyPlaceholder: 'List any allergies or food restrictions',
      yourFeedback: 'Your Feedback',
      feedbackPlaceholder: 'Share your thoughts about the meals',
      saveInformation: 'Save Information',
      infoUpdated: 'Information updated successfully!',
      failedToSave: 'Failed to save information',
      selectRating: 'Please select a rating',
      thankYouRating: 'Thank you for rating the donor!',
      failedToRate: 'Failed to submit rating',
      redirecting: 'Redirecting to Parent Portal...',
      mealPlan: 'Meal Plan',
      scheduledMeals: 'Scheduled Meals',
      assignedToClass: 'Meals assigned to your child\'s class',
      serves: 'Serves',
      kids: 'Kids',
      providedBy: 'Provided by',
      today: 'Today',
      upcomingMealPlans: 'Upcoming Meal Plans',
    },
  },
  si: {
    common: {
      loading: 'පූරණය වෙමින්...',
      save: 'සුරකින්න',
      cancel: 'අවලංගු කරන්න',
      submit: 'ඉදිරිපත් කරන්න',
      delete: 'මකන්න',
      edit: 'සංස්කරණය',
      back: 'ආපසු',
      logout: 'ඉවත් වන්න',
      success: 'සාර්ථකයි',
      error: 'දෝෂයකි',
      refresh: 'නැවුම් කරන්න',
    },
    admin: {
      dashboard: 'පරිපාලක උපකරණ පුවරුව',
      systemManagement: 'පද්ධති කළමනාකරණය',
      todayMeals: 'අද ආහාර',
      totalMealsServed: 'මුළු ආහාර සේවා',
      totalDonations: 'මුළු පරිත්‍යාග',
      pendingRequests: 'පොරොත්තු ඉල්ලීම්',
      systemStatistics: 'පද්ධති සංඛ්‍යාලේඛන',
      totalUsers: 'මුළු පරිශීලකයින්',
      totalSchools: 'මුළු පාසල්',
      pendingSchoolApprovals: 'පොරොත්තු පාසල් අනුමත කිරීම්',
      usersByRole: 'භූමිකාව අනුව පරිශීලකයින්',
      admins: 'පරිපාලකයින්',
      principals: 'විදුහල්පතිවරුන්',
      teachers: 'ගුරුවරුන්',
      donors: 'පරිත්‍යාගශීලීන්',
      parents: 'මව්පියන්',
      quickActions: 'ඉක්මන් ක්‍රියාමාර්ග',
      userManagement: 'පරිශීලක කළමනාකරණය',
      userManagementDesc: 'පරිශීලකයින් එකතු කරන්න, සංස්කරණය කරන්න සහ කළමනාකරණය කරන්න',
      schoolManagement: 'පාසල් කළමනාකරණය',
      schoolManagementDesc: 'පාසල් අනුමත කරන්න',
      donationManagement: 'පරිත්‍යාග කළමනාකරණය',
      donationManagementDesc: 'පරිත්‍යාග ලුහුබඳින්න සහ කළමනාකරණය කරන්න',
      reportsAnalytics: 'වාර්තා සහ විශ්ලේෂණ',
      reportsAnalyticsDesc: 'විස්තීර්ණ වාර්තා ජනනය කරන්න',
      accessDenied: 'ප්‍රවේශය ප්‍රතික්ෂේප විය: පරිපාලක පමණි',
      totalRaised: 'මුළු එකතුව',
      mealsFunded: 'අරමුදල් සහිත ආහාර',
      activeRequests: 'ක්‍රියාකාරී ඉල්ලීම්',
      donations: 'පරිත්‍යාග',
      requests: 'ඉල්ලීම්',
      noDonations: 'තවමත් පරිත්‍යාග නැත',
      noDonationRequests: 'පරිත්‍යාග ඉල්ලීම් නැත',
      donor: 'පරිත්‍යාගශීලියා',
      email: 'විද්‍යුත් තැපැල',
      school: 'පාසල',
      message: 'පණිවිඩය',
      principal: 'විදුහල්පති',
      purpose: 'අරමුණ',
      targetDate: 'ඉලක්කගත දිනය',
      description: 'විස්තරය',
      pending: 'පොරොත්තු',
      approved: 'අනුමත',
      rejected: 'ප්‍රතික්ෂේප',
      total: 'මුළු',
      noSchools: 'පාසල් හමු නොවීය',
      confirmApproval: 'අනුමතය තහවුරු කරන්න',
      approveSchool: 'අනුමත කරන්න',
      confirmRejection: 'ප්‍රතික්ෂේපය තහවුරු කරන්න',
      rejectSchool: 'ප්‍රතික්ෂේප කරන්න',
      schoolApproved: 'පාසල සාර්ථකව අනුමත විය',
      schoolRejected: 'පාසල ප්‍රතික්ෂේප විය',
      failedToApprove: 'පාසල අනුමත කිරීමට අසමත් විය',
      failedToReject: 'පාසල ප්‍රතික්ෂේප කිරීමට අසමත් විය',
      submitted: 'ඉදිරිපත් කළ',
      addNewUser: 'නව පරිශීලකයෙකු එක් කරන්න',
      editUser: 'පරිශීලකයා සංස්කරණය කරන්න',
      name: 'නම',
      password: 'මුරපදය',
      role: 'භූමිකාව',
      schoolOptional: 'පාසල (විකල්ප)',
      none: 'කිසිවක් නැත',
      create: 'සාදන්න',
      update: 'යාවත්කාලීන කරන්න',
      confirmDelete: 'මැකීම තහවුරු කරන්න',
      deleteMessage: 'ඔබට මකා දැමීමට අවශ්‍යද',
      userCreated: 'පරිශීලකයා සාර්ථකව සාදන ලදී',
      userUpdated: 'පරිශීලකයා සාර්ථකව යාවත්කාලීන විය',
      userDeleted: 'පරිශීලකයා සාර්ථකව මකා දමන ලදී',
      fillRequired: 'කරුණාකර අවශ්‍ය සියලුම ක්ෂේත්‍ර පුරවන්න',
      passwordRequired: 'නව පරිශීලකයින් සඳහා මුරපදය අවශ්‍ය වේ',
      users: 'පරිශීලකයින්',
      schools: 'පාසල්',
    },
    reports: {
      generatedReports: 'ජනනය කළ වාර්තා',
      generateWithAI: 'AI සමඟ ජනනය කරන්න',
      report: 'වාර්තාව',
      aiGenerated: 'AI ජනනය කළ',
      mealsServed: 'සේවා කළ ආහාර',
      shortages: 'හිඟයන්',
      feedbackSummary: 'ප්‍රතිචාර සාරාංශය',
      downloadPDF: 'PDF බාගන්න',
      share: 'බෙදාගන්න',
      noReports: 'තවමත් වාර්තා ජනනය කර නැත',
      useAIPrompt: 'ඔබේ පළමු වාර්තාව ජනනය කිරීමට AI භාවිතා කරන්න',
      generateAIReport: 'AI වාර්තාව ජනනය කරන්න',
      reportPeriod: 'වාර්තා කාල පරිච්ඡේදය (දින)',
      dataAnalyzed: 'අවසාන',
      daysAnalyzed: 'දින දත්ත විශ්ලේෂණය කරනු ලැබේ',
      generateReport: 'වාර්තාව ජනනය කරන්න',
      reportGenerated: 'වාර්තාව ජනනය කරන ලදී!',
      reportSuccess: 'ඔබේ AI බලගැන්වූ වාර්තාව සාර්ථකව ජනනය කර ඇත. එය බෙදා ගැනීමට හෝ සුරැකීමට පහත විකල්පයක් තෝරන්න.',
      shareReport: 'වාර්තාව බෙදාගන්න',
      printSavePDF: 'මුද්‍රණය/PDF ලෙස සුරකින්න',
      shareViaPDF: 'යෙදුම් හරහා PDF බෙදාගන්න',
      savePDF: 'PDF සුරකින්න සහ බෙදාගන්න',
      close: 'වසන්න',
      accessDeniedReports: 'ප්‍රවේශය ප්‍රතික්ෂේප විය',
      noPermission: 'මෙම පිටුව බැලීමට ඔබට අවසර නැත.',
      failedGenerate: 'වාර්තාව ජනනය කිරීමට අසමත් විය. කරුණාකර නැවත උත්සාහ කරන්න.',
      failedShare: 'වාර්තාව බෙදාගැනීමට අසමත් විය. කරුණාකර නැවත උත්සාහ කරන්න.',
      failedDownload: 'වාර්තාව බාගැනීමට අසමත් විය. කරුණාකර නැවත උත්සාහ කරන්න.',
    },
    feedback: {
      schoolFeedback: 'පාසල් ප්‍රතිචාරය',
      allFeedback: 'සියලුම ප්‍රතිචාර',
      pending: 'පොරොත්තු',
      reviewed: 'සමාලෝචනය කළ',
      noFeedback: 'තවමත් ප්‍රතිචාර නැත',
      school: 'පාසල',
      submittedBy: 'ඉදිරිපත් කළේ',
      status: 'තත්ත්වය',
      markReviewed: 'සමාලෝචනය කළ ලෙස සලකුණු කරන්න',
      feedbackMarked: 'ප්‍රතිචාරය සමාලෝචනය කළ ලෙස සලකුණු කරන ලදී',
      failedMark: 'ප්‍රතිචාරය සලකුණු කිරීමට අසමත් විය',
    },
    donations: {
      donations: 'පරිත්‍යාග',
      claimDonation: 'පරිත්‍යාගය ඉල්ලන්න',
      noDonations: 'පරිත්‍යාග නොමැත',
      donatedBy: 'පරිත්‍යාග කළේ',
      amount: 'ප්‍රමාණය',
      forStudents: 'සිසුන් සඳහා',
      claimSuccess: 'පරිත්‍යාගය සාර්ථකව ඉල්ලා ගන්නා ලදී!',
      failedClaim: 'පරිත්‍යාගය ඉල්ලා ගැනීමට අසමත් විය',
    },
    parent: {
      hello: 'ආයුබෝවන්',
      mealInfo: 'ගේ ආහාර තොරතුරු',
      yourAccessCode: 'ඔබේ ප්‍රවේශ කේතය',
      grade: 'ශ්‍රේණිය',
      age: 'වයස',
      todayMeal: 'අද ආහාරය',
      amount: 'ප්‍රමාණය',
      for: 'සඳහා',
      students: 'සිසුන්',
      donatedBy: 'පරිත්‍යාග කළේ',
      ratings: 'ශ්‍රේණිගත කිරීම්',
      howWasMeal: 'ආහාරය කොහොමද?',
      tapStars: 'ශ්‍රේණිගත කිරීමට තරු තට්ටු කරන්න',
      poor: 'දුර්වල',
      fair: 'සාධාරණ',
      good: 'හොඳයි',
      veryGood: 'ඉතා හොඳයි',
      excellent: 'විශිෂ්ටයි',
      addComment: 'ඔබේ අදහස එක් කරන්න (විකල්ප)',
      submitRating: 'ශ්‍රේණිගත කිරීම ඉදිරිපත් කරන්න',
      noMealToday: 'අද ආහාරයක් නැත',
      noMealScheduled: 'අද සඳහා ආහාරයක් කාලසටහන්ගත කර නැත',
      mealStatus: 'ආහාර තත්ත්වය',
      mealServed: '✓ ආහාරය සේවය කළා',
      notServedYet: '⏳ තවම සේවය කර නැත',
      at: 'දී',
      teacherNote: 'ගුරුවරයාගේ සටහන:',
      upcomingMeals: 'ඉදිරි ආහාර',
      by: 'විසින්',
      itemsPlanned: 'අයිතම සැලසුම් කර ඇත',
      allergyInfo: 'අසාත්මිකතා තොරතුරු',
      allergyPlaceholder: 'අසාත්මිකතා හෝ ආහාර සීමා කිරීම් ලැයිස්තුගත කරන්න',
      yourFeedback: 'ඔබේ ප්‍රතිචාරය',
      feedbackPlaceholder: 'ආහාර පිළිබඳව ඔබේ අදහස් බෙදා ගන්න',
      saveInformation: 'තොරතුරු සුරකින්න',
      infoUpdated: 'තොරතුරු සාර්ථකව යාවත්කාලීන විය!',
      failedToSave: 'තොරතුරු සුරැකීමට අසමත් විය',
      selectRating: 'කරුණාකර ශ්‍රේණිගත කිරීමක් තෝරන්න',
      thankYouRating: 'පරිත්‍යාගශීලියා ශ්‍රේණිගත කිරීම ගැන ස්තූතියි!',
      failedToRate: 'ශ්‍රේණිගත කිරීම ඉදිරිපත් කිරීමට අසමත් විය',
      redirecting: 'මව්පිය ද්වාරය වෙත හරවා යවමින්...',
      mealPlan: 'ආහාර සැලැස්ම',
      scheduledMeals: 'කාලසටහන්ගත ආහාර',
      assignedToClass: 'ඔබේ දරුවාගේ පන්තියට පවරා ඇති ආහාර',
      serves: 'සේවා කරයි',
      kids: 'දරුවන්',
      providedBy: 'සපයන ලද',
      today: 'අද',
      upcomingMealPlans: 'ඉදිරි ආහාර සැලැස්ම්',
    },
  },
  ta: {
    common: {
      loading: 'ஏற்றுகிறது...',
      save: 'சேமிக்கவும்',
      cancel: 'ரத்துசெய்',
      submit: 'சமர்ப்பிக்கவும்',
      delete: 'அழிக்கவும்',
      edit: 'திருத்தவும்',
      back: 'பின்செல்',
      logout: 'வெளியேறு',
      success: 'வெற்றி',
      error: 'பிழை',
      refresh: 'புதுப்பிக்கவும்',
    },
    admin: {
      dashboard: 'நிர்வாக டாஷ்போர்டு',
      systemManagement: 'அமைப்பு மேலாண்மை',
      todayMeals: 'இன்றைய உணவுகள்',
      totalMealsServed: 'மொத்த உணவு சேவைகள்',
      totalDonations: 'மொத்த நன்கொடைகள்',
      pendingRequests: 'நிலுவையிலுள்ள கோரிக்கைகள்',
      systemStatistics: 'அமைப்பு புள்ளிவிவரங்கள்',
      totalUsers: 'மொத்த பயனர்கள்',
      totalSchools: 'மொத்த பள்ளிகள்',
      pendingSchoolApprovals: 'நிலுவையிலுள்ள பள்ளி ஒப்புதல்கள்',
      usersByRole: 'பங்கு வாரியாக பயனர்கள்',
      admins: 'நிர்வாகிகள்',
      principals: 'முதல்வர்கள்',
      teachers: 'ஆசிரியர்கள்',
      donors: 'நன்கொடையாளர்கள்',
      parents: 'பெற்றோர்கள்',
      quickActions: 'விரைவு செயல்கள்',
      userManagement: 'பயனர் மேலாண்மை',
      userManagementDesc: 'பயனர்களைச் சேர்க்கவும், திருத்தவும் மற்றும் நிர்வகிக்கவும்',
      schoolManagement: 'பள்ளி மேலாண்மை',
      schoolManagementDesc: 'பள்ளிகளை அங்கீகரிக்கவும்',
      donationManagement: 'நன்கொடை மேலாண்மை',
      donationManagementDesc: 'நன்கொடைகளைக் கண்காணிக்கவும் மற்றும் நிர்வகிக்கவும்',
      reportsAnalytics: 'அறிக்கைகள் மற்றும் பகுப்பாய்வு',
      reportsAnalyticsDesc: 'விரிவான அறிக்கைகளை உருவாக்கவும்',
      accessDenied: 'அணுகல் மறுக்கப்பட்டது: நிர்வாகி மட்டும்',
      totalRaised: 'மொத்த திரட்டப்பட்டது',
      mealsFunded: 'நிதி வழங்கப்பட்ட உணவுகள்',
      activeRequests: 'செயலில் உள்ள கோரிக்கைகள்',
      donations: 'நன்கொடைகள்',
      requests: 'கோரிக்கைகள்',
      noDonations: 'இன்னும் நன்கொடைகள் இல்லை',
      noDonationRequests: 'நன்கொடை கோரிக்கைகள் இல்லை',
      donor: 'நன்கொடையாளர்',
      email: 'மின்னஞ்சல்',
      school: 'பள்ளி',
      message: 'செய்தி',
      principal: 'முதல்வர்',
      purpose: 'நோக்கம்',
      targetDate: 'இலக்கு தேதி',
      description: 'விளக்கம்',
      pending: 'நிலுவை',
      approved: 'அங்கீகரிக்கப்பட்டது',
      rejected: 'நிராகரிக்கப்பட்டது',
      total: 'மொத்தம்',
      noSchools: 'பள்ளிகள் எதுவும் கிடைக்கவில்லை',
      confirmApproval: 'ஒப்புதலை உறுதிப்படுத்தவும்',
      approveSchool: 'அங்கீகரிக்கவும்',
      confirmRejection: 'நிராகரிப்பை உறுதிப்படுத்தவும்',
      rejectSchool: 'நிராகரிக்கவும்',
      schoolApproved: 'பள்ளி வெற்றிகரமாக அங்கீகரிக்கப்பட்டது',
      schoolRejected: 'பள்ளி நிராகரிக்கப்பட்டது',
      failedToApprove: 'பள்ளியை அங்கீகரிக்கத் தவறிவிட்டது',
      failedToReject: 'பள்ளியை நிராகரிக்கத் தவறிவிட்டது',
      submitted: 'சமர்ப்பிக்கப்பட்டது',
      addNewUser: 'புதிய பயனரைச் சேர்க்கவும்',
      editUser: 'பயனரைத் திருத்தவும்',
      name: 'பெயர்',
      password: 'கடவுச்சொல்',
      role: 'பங்கு',
      schoolOptional: 'பள்ளி (விருப்பம்)',
      none: 'எதுவுமில்லை',
      create: 'உருவாக்கவும்',
      update: 'புதுப்பிக்கவும்',
      confirmDelete: 'நீக்குதலை உறுதிப்படுத்தவும்',
      deleteMessage: 'நீக்க விரும்புகிறீர்களா',
      userCreated: 'பயனர் வெற்றிகரமாக உருவாக்கப்பட்டார்',
      userUpdated: 'பயனர் வெற்றிகரமாக புதுப்பிக்கப்பட்டார்',
      userDeleted: 'பயனர் வெற்றிகரமாக நீக்கப்பட்டார்',
      fillRequired: 'தயவுசெய்து அனைத்து தேவையான புலங்களையும் நிரப்பவும்',
      passwordRequired: 'புதிய பயனர்களுக்கு கடவுச்சொல் தேவை',
      users: 'பயனர்கள்',
      schools: 'பள்ளிகள்',
    },
    reports: {
      generatedReports: 'உருவாக்கப்பட்ட அறிக்கைகள்',
      generateWithAI: 'AI உடன் உருவாக்கவும்',
      report: 'அறிக்கை',
      aiGenerated: 'AI உருவாக்கியது',
      mealsServed: 'வழங்கப்பட்ட உணவுகள்',
      shortages: 'பற்றாக்குறைகள்',
      feedbackSummary: 'கருத்து சுருக்கம்',
      downloadPDF: 'PDF பதிவிறக்கவும்',
      share: 'பகிரவும்',
      noReports: 'இன்னும் அறிக்கைகள் உருவாக்கப்படவில்லை',
      useAIPrompt: 'உங்கள் முதல் அறிக்கையை உருவாக்க AI ஐப் பயன்படுத்தவும்',
      generateAIReport: 'AI அறிக்கையை உருவாக்கவும்',
      reportPeriod: 'அறிக்கை காலம் (நாட்கள்)',
      dataAnalyzed: 'கடைசி',
      daysAnalyzed: 'நாட்களின் தரவு பகுப்பாய்வு செய்யப்படும்',
      generateReport: 'அறிக்கையை உருவாக்கவும்',
      reportGenerated: 'அறிக்கை உருவாக்கப்பட்டது!',
      reportSuccess: 'உங்கள் AI இயக்கப்பட்ட அறிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது. அதைப் பகிர அல்லது சேமிக்க கீழே ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.',
      shareReport: 'அறிக்கையைப் பகிரவும்',
      printSavePDF: 'அச்சிடு/PDF ஆக சேமிக்கவும்',
      shareViaPDF: 'பயன்பாடுகள் வழியாக PDF பகிரவும்',
      savePDF: 'PDF சேமித்து பகிரவும்',
      close: 'மூடவும்',
      accessDeniedReports: 'அணுகல் மறுக்கப்பட்டது',
      noPermission: 'இந்தப் பக்கத்தைப் பார்க்க உங்களுக்கு அனுமதி இல்லை.',
      failedGenerate: 'அறிக்கையை உருவாக்கத் தவறிவிட்டது. மீண்டும் முயற்சிக்கவும்.',
      failedShare: 'அறிக்கையைப் பகிரத் தவறிவிட்டது. மீண்டும் முயற்சிக்கவும்.',
      failedDownload: 'அறிக்கையைப் பதிவிறக்கத் தவறிவிட்டது. மீண்டும் முயற்சிக்கவும்.',
    },
    feedback: {
      schoolFeedback: 'பள்ளி கருத்து',
      allFeedback: 'அனைத்து கருத்துகள்',
      pending: 'நிலுவை',
      reviewed: 'மதிப்பாய்வு செய்யப்பட்டது',
      noFeedback: 'இன்னும் கருத்துகள் இல்லை',
      school: 'பள்ளி',
      submittedBy: 'சமர்ப்பித்தவர்',
      status: 'நிலை',
      markReviewed: 'மதிப்பாய்வு செய்ததாகக் குறிக்கவும்',
      feedbackMarked: 'கருத்து மதிப்பாய்வு செய்ததாகக் குறிக்கப்பட்டது',
      failedMark: 'கருத்தைக் குறிக்கத் தவறிவிட்டது',
    },
    donations: {
      donations: 'நன்கொடைகள்',
      claimDonation: 'நன்கொடையைக் கோரவும்',
      noDonations: 'நன்கொடைகள் எதுவும் இல்லை',
      donatedBy: 'நன்கொடையாக',
      amount: 'தொகை',
      forStudents: 'மாணவர்களுக்கு',
      claimSuccess: 'நன்கொடை வெற்றிகரமாகக் கோரப்பட்டது!',
      failedClaim: 'நன்கொடையைக் கோரத் தவறிவிட்டது',
    },
    parent: {
      hello: 'வணக்கம்',
      mealInfo: 'இன் உணவுத் தகவல்',
      yourAccessCode: 'உங்கள் அணுகல் குறியீடு',
      grade: 'வகுப்பு',
      age: 'வயது',
      todayMeal: 'இன்றைய உணவு',
      amount: 'அளவு',
      for: 'க்கு',
      students: 'மாணவர்கள்',
      donatedBy: 'நன்கொடையாக',
      ratings: 'மதிப்பீடுகள்',
      howWasMeal: 'உணவு எப்படி இருந்தது?',
      tapStars: 'மதிப்பிட நட்சத்திரங்களைத் தட்டவும்',
      poor: 'மோசம்',
      fair: 'நியாயம்',
      good: 'நல்லது',
      veryGood: 'மிகவும் நல்லது',
      excellent: 'சிறப்பானது',
      addComment: 'உங்கள் கருத்தைச் சேர்க்கவும் (விருப்பம்)',
      submitRating: 'மதிப்பீட்டைச் சமர்ப்பிக்கவும்',
      noMealToday: 'இன்று உணவு இல்லை',
      noMealScheduled: 'இன்றுக்கு உணவு திட்டமிடப்படவில்லை',
      mealStatus: 'உணவு நிலை',
      mealServed: '✓ உணவு வழங்கப்பட்டது',
      notServedYet: '⏳ இன்னும் வழங்கப்படவில்லை',
      at: 'இல்',
      teacherNote: 'ஆசிரியரின் குறிப்பு:',
      upcomingMeals: 'வரவிருக்கும் உணவுகள்',
      by: 'மூலம்',
      itemsPlanned: 'பொருட்கள் திட்டமிடப்பட்டுள்ளன',
      allergyInfo: 'ஒவ்வாமை தகவல்',
      allergyPlaceholder: 'எந்த ஒவ்வாமை அல்லது உணவு தடைகளையும் பட்டியலிடுங்கள்',
      yourFeedback: 'உங்கள் கருத்து',
      feedbackPlaceholder: 'உணவுகள் பற்றிய உங்கள் எண்ணங்களைப் பகிரவும்',
      saveInformation: 'தகவலைச் சேமிக்கவும்',
      infoUpdated: 'தகவல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      failedToSave: 'தகவலைச் சேமிக்கத் தவறிவிட்டது',
      selectRating: 'தயவுசெய்து ஒரு மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
      thankYouRating: 'நன்கொடையாளரை மதிப்பிட்டதற்கு நன்றி!',
      failedToRate: 'மதிப்பீட்டைச் சமர்ப்பிக்கத் தவறிவிட்டது',
      redirecting: 'பெற்றோர் போர்ட்டலுக்கு திருப்பிவிடப்படுகிறது...',
      mealPlan: 'உணவுத் திட்டம்',
      scheduledMeals: 'திட்டமிடப்பட்ட உணவுகள்',
      assignedToClass: 'உங்கள் குழந்தையின் வகுப்பிற்கு ஒதுக்கப்பட்ட உணவுகள்',
      serves: 'வழங்குகிறது',
      kids: 'குழந்தைகள்',
      providedBy: 'வழங்கியவர்',
      today: 'இன்று',
      upcomingMealPlans: 'வரவிருக்கும் உணவுத் திட்டங்கள்',
    },
  },
};
